import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Back Button */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to PDF Lab Pro
        </Link>

        {/* Header */}
        <div className="mb-12">
          <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-muted-foreground">
            Last Updated: <span className="font-medium">October 27, 2025</span>
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">
          {/* Introduction */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
            <p className="text-muted-foreground leading-relaxed">
              At pdflab.pro, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose,
              and safeguard your information when you use our service. Please read this privacy policy carefully.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              By using pdflab.pro, you agree to the collection and use of information in accordance with this policy.
              If you do not agree with this policy, please do not use our service.
            </p>
          </section>

          {/* 1. Information We Collect */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Information We Collect</h2>

            <h3 className="text-xl font-medium mb-3 mt-6">1.1 Personal Information</h3>
            <p className="text-muted-foreground leading-relaxed">
              When you create an account, we collect:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Name:</strong> First and last name</li>
              <li><strong>Email Address:</strong> For account creation and communication</li>
              <li><strong>Password:</strong> Encrypted and stored securely</li>
              <li><strong>Payment Information:</strong> Processed securely through Stripe (we do not store card details)</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">1.2 File Data</h3>
            <p className="text-muted-foreground leading-relaxed">
              When you use our conversion services:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Uploaded Files:</strong> PDFs and documents you upload for processing</li>
              <li><strong>Converted Files:</strong> Output files generated by our service</li>
              <li><strong>File Metadata:</strong> File names, sizes, formats, and upload timestamps</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4 bg-amber-500/10 border border-amber-500/20 rounded-lg p-4">
              <strong>Important:</strong> All uploaded and converted files are automatically deleted from our servers
              within 1 hour of processing. We do not permanently store your file contents.
            </p>

            <h3 className="text-xl font-medium mb-3 mt-6">1.3 Usage Data</h3>
            <p className="text-muted-foreground leading-relaxed">
              We automatically collect certain information when you use the service:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Device Information:</strong> Browser type, operating system, device type</li>
              <li><strong>IP Address:</strong> For security and fraud prevention</li>
              <li><strong>Usage Statistics:</strong> Conversion counts, feature usage, page views</li>
              <li><strong>Cookies:</strong> Session cookies for authentication and preferences</li>
            </ul>
          </section>

          {/* 2. How We Use Your Information */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">2. How We Use Your Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              We use the collected information for:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Service Provision:</strong> To provide, maintain, and improve our PDF conversion services</li>
              <li><strong>Account Management:</strong> To create and manage your user account</li>
              <li><strong>Payment Processing:</strong> To process subscription payments and billing</li>
              <li><strong>Communication:</strong> To send service updates, security alerts, and support messages</li>
              <li><strong>Usage Limits:</strong> To enforce subscription tiers and usage limits</li>
              <li><strong>Security:</strong> To detect and prevent fraud, abuse, and security threats</li>
              <li><strong>Analytics:</strong> To understand how users interact with our service and improve user experience</li>
              <li><strong>Legal Compliance:</strong> To comply with legal obligations and enforce our Terms of Service</li>
            </ul>
          </section>

          {/* 3. File Processing and Storage */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">3. File Processing and Storage</h2>

            <h3 className="text-xl font-medium mb-3 mt-6">3.1 Temporary Processing</h3>
            <p className="text-muted-foreground leading-relaxed">
              When you upload a file:
            </p>
            <ol className="list-decimal list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>File is securely uploaded to our server via HTTPS</li>
              <li>File is processed in memory or temporary storage</li>
              <li>Converted file is generated and made available for download</li>
              <li>Both original and converted files are deleted within 1 hour</li>
            </ol>

            <h3 className="text-xl font-medium mb-3 mt-6">3.2 No Long-Term Storage</h3>
            <p className="text-muted-foreground leading-relaxed">
              We <strong>DO NOT</strong>:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Permanently store your uploaded files</li>
              <li>Use your files for training AI models</li>
              <li>Share your file contents with third parties</li>
              <li>Analyze file contents except as necessary for conversion</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">3.3 Metadata Retention</h3>
            <p className="text-muted-foreground leading-relaxed">
              We retain limited metadata (file name, size, timestamp) for:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Usage statistics and billing</li>
              <li>Service improvement and analytics</li>
              <li>Fraud prevention and security monitoring</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              File contents are NOT retained beyond the 1-hour processing window.
            </p>
          </section>

          {/* 4. Information Sharing */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">4. How We Share Your Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              We do not sell your personal information. We may share information with:
            </p>

            <h3 className="text-xl font-medium mb-3 mt-6">4.1 Service Providers</h3>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Stripe:</strong> For payment processing (subject to Stripe&apos;s privacy policy)</li>
              <li><strong>Hosting Providers:</strong> For server infrastructure and file processing</li>
              <li><strong>Analytics Services:</strong> For usage analytics (anonymized where possible)</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">4.2 Legal Requirements</h3>
            <p className="text-muted-foreground leading-relaxed">
              We may disclose information if required to:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Comply with legal obligations or court orders</li>
              <li>Protect our rights, property, or safety</li>
              <li>Investigate fraud or security issues</li>
              <li>Prevent harm to users or the public</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">4.3 Business Transfers</h3>
            <p className="text-muted-foreground leading-relaxed">
              If pdflab.pro is involved in a merger, acquisition, or sale, your information may be transferred.
              We will notify you before your information is transferred and becomes subject to a different privacy policy.
            </p>
          </section>

          {/* 5. Data Security */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">5. Data Security</h2>
            <p className="text-muted-foreground leading-relaxed">
              We implement security measures to protect your information:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Encryption:</strong> HTTPS/TLS for all data transmission</li>
              <li><strong>Password Security:</strong> Passwords are hashed using industry-standard algorithms</li>
              <li><strong>Access Controls:</strong> Limited employee access to personal data</li>
              <li><strong>Automatic Deletion:</strong> Files deleted within 1 hour of processing</li>
              <li><strong>Regular Audits:</strong> Security assessments and vulnerability testing</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4 bg-amber-500/10 border border-amber-500/20 rounded-lg p-4">
              <strong>Important:</strong> No method of transmission over the internet is 100% secure. While we strive to
              protect your data, we cannot guarantee absolute security.
            </p>
          </section>

          {/* 6. Your Privacy Rights */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Your Privacy Rights</h2>

            <h3 className="text-xl font-medium mb-3 mt-6">6.1 General Rights</h3>
            <p className="text-muted-foreground leading-relaxed">
              You have the right to:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Access:</strong> Request a copy of your personal data</li>
              <li><strong>Correction:</strong> Update or correct inaccurate information</li>
              <li><strong>Deletion:</strong> Request deletion of your account and data</li>
              <li><strong>Portability:</strong> Export your data in a machine-readable format</li>
              <li><strong>Objection:</strong> Object to certain data processing activities</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">6.2 GDPR Rights (EU Users)</h3>
            <p className="text-muted-foreground leading-relaxed">
              If you are in the European Union, you have additional rights under GDPR:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Right to withdraw consent at any time</li>
              <li>Right to lodge a complaint with a supervisory authority</li>
              <li>Right to restriction of processing</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">6.3 CCPA Rights (California Users)</h3>
            <p className="text-muted-foreground leading-relaxed">
              If you are a California resident, you have rights under CCPA:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Right to know what personal information is collected</li>
              <li>Right to delete personal information</li>
              <li>Right to opt-out of the sale of personal information (we do not sell your data)</li>
              <li>Right to non-discrimination for exercising your rights</li>
            </ul>

            <h3 className="text-xl font-medium mb-3 mt-6">6.4 Exercising Your Rights</h3>
            <p className="text-muted-foreground leading-relaxed">
              To exercise any of these rights, contact us at: <strong>privacy@pdflab.pro</strong>
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              We will respond to your request within 30 days.
            </p>
          </section>

          {/* 7. Cookies and Tracking */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Cookies and Tracking Technologies</h2>
            <p className="text-muted-foreground leading-relaxed">
              We use cookies and similar technologies for:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Essential Cookies:</strong> Required for authentication and security</li>
              <li><strong>Preference Cookies:</strong> Remember your settings and preferences</li>
              <li><strong>Analytics Cookies:</strong> Understand how users interact with our service</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              You can control cookies through your browser settings. However, disabling essential cookies may affect
              service functionality.
            </p>
          </section>

          {/* 8. Data Retention */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Data Retention</h2>
            <p className="text-muted-foreground leading-relaxed">
              We retain different types of data for varying periods:
            </p>
            <div className="bg-card border rounded-lg p-6 mt-4 space-y-3">
              <div>
                <h3 className="font-semibold">File Contents</h3>
                <p className="text-sm text-muted-foreground">Deleted within 1 hour of processing</p>
              </div>
              <div>
                <h3 className="font-semibold">Account Information</h3>
                <p className="text-sm text-muted-foreground">Retained until account deletion</p>
              </div>
              <div>
                <h3 className="font-semibold">Usage Metadata</h3>
                <p className="text-sm text-muted-foreground">Retained for 12 months for analytics</p>
              </div>
              <div>
                <h3 className="font-semibold">Payment Records</h3>
                <p className="text-sm text-muted-foreground">Retained for 7 years for tax compliance</p>
              </div>
            </div>
          </section>

          {/* 9. Children's Privacy */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">9. Children&apos;s Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              pdflab.pro is not intended for users under the age of 16. We do not knowingly collect personal
              information from children under 16. If you believe we have inadvertently collected information from a
              child under 16, please contact us immediately at privacy@pdflab.pro.
            </p>
          </section>

          {/* 10. International Data Transfers */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">10. International Data Transfers</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your information may be transferred to and processed in countries other than your own. We ensure
              appropriate safeguards are in place:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Standard contractual clauses approved by the European Commission</li>
              <li>Adequacy decisions for data transfers</li>
              <li>Encryption during transmission and storage</li>
            </ul>
          </section>

          {/* 11. Third-Party Links */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Third-Party Links</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our service may contain links to third-party websites. We are not responsible for the privacy practices
              of these external sites. We encourage you to read their privacy policies before providing any information.
            </p>
          </section>

          {/* 12. Changes to This Policy */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Changes to This Privacy Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this Privacy Policy from time to time. We will notify you of material changes by:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li>Posting the new Privacy Policy on this page</li>
              <li>Updating the &quot;Last Updated&quot; date</li>
              <li>Sending an email notification (for material changes)</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Continued use of the service after changes constitutes acceptance of the updated Privacy Policy.
            </p>
          </section>

          {/* 13. Contact Us */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">13. Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions, concerns, or requests regarding this Privacy Policy or your personal data:
            </p>
            <div className="bg-card border rounded-lg p-6 mt-4">
              <p className="text-sm text-muted-foreground">
                <strong>Privacy Team:</strong> privacy@pdflab.pro
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                <strong>General Support:</strong> support@pdflab.pro
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                <strong>Website:</strong> https://pdflab.pro
              </p>
            </div>
            <p className="text-muted-foreground leading-relaxed mt-4">
              We will respond to your inquiries within 30 days.
            </p>
          </section>

          {/* 14. Legal Basis */}
          <section>
            <h2 className="text-2xl font-semibold mb-4">14. Legal Basis for Processing (GDPR)</h2>
            <p className="text-muted-foreground leading-relaxed">
              For EU users, we process your personal data under the following legal bases:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4 ml-4">
              <li><strong>Contract:</strong> Processing necessary to provide the service you signed up for</li>
              <li><strong>Consent:</strong> You have given clear consent for specific processing activities</li>
              <li><strong>Legitimate Interest:</strong> For fraud prevention, security, and service improvement</li>
              <li><strong>Legal Obligation:</strong> To comply with applicable laws and regulations</li>
            </ul>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t">
          <p className="text-sm text-muted-foreground text-center">
            Your privacy is important to us. We are committed to protecting your personal information and being
            transparent about our data practices.
          </p>
          <div className="flex justify-center gap-6 mt-6">
            <Link href="/terms" className="text-sm text-primary hover:underline">
              Terms of Service
            </Link>
            <Link href="/" className="text-sm text-primary hover:underline">
              Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
