"""Add subscriptions and payment_logs tables

Revision ID: bfd028ba583f
Revises: 67becfdb392d
Create Date: 2025-10-30 12:55:25.749088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfd028ba583f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'PENDING', name='subscriptionstatus'), nullable=False),
    sa.Column('payfast_token', sa.String(length=255), nullable=True, comment='PayFast subscription token for recurring payments'),
    sa.Column('payfast_subscription_id', sa.String(length=255), nullable=True, comment='PayFast subscription ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Subscription amount in currency'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (USD for United States Dollar)'),
    sa.Column('billing_date', sa.DateTime(), nullable=True, comment='First billing date'),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True, comment='Next billing date for recurring subscription'),
    sa.Column('cancel_at', sa.DateTime(), nullable=True, comment='Scheduled cancellation date'),
    sa.Column('canceled_at', sa.DateTime(), nullable=True, comment='Actual cancellation timestamp'),
    sa.Column('trial_end', sa.DateTime(), nullable=True, comment='Trial period end date'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='Subscription start date'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='Subscription end date (if canceled)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_next_billing_date'), 'subscriptions', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_payfast_token'), 'subscriptions', ['payfast_token'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('payment_logs',
    sa.Column('id', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36), nullable=False),
    sa.Column('subscription_id', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=False, comment='Our internal transaction ID (m_payment_id)'),
    sa.Column('payfast_payment_id', sa.String(length=255), nullable=True, comment='PayFast payment ID (pf_payment_id)'),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'SUBSCRIPTION_PAYMENT', 'ONE_TIME', 'REFUND', name='paymenttype'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'FAILED', 'PENDING', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=10, scale=2), nullable=False, comment='Gross amount before fees'),
    sa.Column('amount_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='PayFast processing fee'),
    sa.Column('amount_net', sa.Numeric(precision=10, scale=2), nullable=False, comment='Net amount after fees'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False, comment='Plan name (free, starter, pro, enterprise)'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='Payment method used (eft, credit_card, etc.)'),
    sa.Column('name_first', sa.String(length=255), nullable=False),
    sa.Column('name_last', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True, comment='Custom data sent to PayFast'),
    sa.Column('itn_data', sa.JSON(), nullable=True, comment='Full ITN notification data from PayFast'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if payment failed'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When the payment was processed'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_logs_created_at'), 'payment_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_logs_payfast_payment_id'), 'payment_logs', ['payfast_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_logs_status'), 'payment_logs', ['status'], unique=False)
    op.create_index(op.f('ix_payment_logs_subscription_id'), 'payment_logs', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_logs_transaction_id'), 'payment_logs', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_logs_user_id'), 'payment_logs', ['user_id'], unique=False)
    op.alter_column('conversion_jobs', 'type',
               existing_type=mysql.ENUM('pdf_to_pptx', 'pdf_to_docx', 'pdf_to_xlsx', 'pdf_to_images', 'pdf_merge'),
               type_=sa.Enum('pdf_to_pptx', 'pdf_to_docx', 'pdf_to_xlsx', 'pdf_to_images', 'pdf_merge', name='conversiontype', native_enum=False),
               existing_comment='Type of conversion',
               existing_nullable=False)
    op.alter_column('conversion_jobs', 'status',
               existing_type=mysql.ENUM('pending', 'queued', 'processing', 'completed', 'failed'),
               type_=sa.Enum('pending', 'queued', 'processing', 'completed', 'failed', name='jobstatus', native_enum=False),
               existing_comment='Current job status',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index(op.f('conversion_jobs_user_id'), table_name='conversion_jobs')
    op.create_index(op.f('ix_conversion_jobs_cloudconvert_job_id'), 'conversion_jobs', ['cloudconvert_job_id'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_created_at'), 'conversion_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_expires_at'), 'conversion_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_status'), 'conversion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_user_id'), 'conversion_jobs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'conversion_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36),
               comment='Unique user identifier (UUID)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               comment="User's email address",
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='Bcrypt hashed password',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment="User's display name",
               existing_nullable=True)
    op.alter_column('users', 'plan',
               existing_type=mysql.ENUM('free', 'starter', 'pro', 'enterprise'),
               type_=sa.Enum('free', 'starter', 'pro', 'enterprise', name='userplan', native_enum=False),
               comment='Current subscription plan',
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
    op.alter_column('users', 'conversions_used',
               existing_type=mysql.INTEGER(),
               comment='Number of conversions used this month',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'conversions_limit',
               existing_type=mysql.INTEGER(),
               comment='Monthly conversion limit',
               existing_nullable=False,
               existing_server_default=sa.text("'3'"))
    op.alter_column('users', 'stripe_customer_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='Stripe customer ID (legacy)',
               existing_nullable=True)
    op.alter_column('users', 'subscription_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='Active subscription ID',
               existing_nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=mysql.ENUM('active', 'canceled', 'past_due', 'trialing'),
               type_=sa.Enum('active', 'canceled', 'past_due', 'trialing', name='subscriptionstatus', native_enum=False),
               comment='Current subscription status',
               existing_nullable=True)
    op.alter_column('users', 'subscription_end_date',
               existing_type=mysql.DATETIME(),
               comment='Subscription expiration date',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment='Last login timestamp',
               existing_nullable=True)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('email_10'), table_name='users')
    op.drop_index(op.f('email_11'), table_name='users')
    op.drop_index(op.f('email_12'), table_name='users')
    op.drop_index(op.f('email_13'), table_name='users')
    op.drop_index(op.f('email_14'), table_name='users')
    op.drop_index(op.f('email_15'), table_name='users')
    op.drop_index(op.f('email_16'), table_name='users')
    op.drop_index(op.f('email_17'), table_name='users')
    op.drop_index(op.f('email_18'), table_name='users')
    op.drop_index(op.f('email_19'), table_name='users')
    op.drop_index(op.f('email_2'), table_name='users')
    op.drop_index(op.f('email_20'), table_name='users')
    op.drop_index(op.f('email_3'), table_name='users')
    op.drop_index(op.f('email_4'), table_name='users')
    op.drop_index(op.f('email_5'), table_name='users')
    op.drop_index(op.f('email_6'), table_name='users')
    op.drop_index(op.f('email_7'), table_name='users')
    op.drop_index(op.f('email_8'), table_name='users')
    op.drop_index(op.f('email_9'), table_name='users')
    op.drop_index(op.f('users_email'), table_name='users')
    op.drop_index(op.f('users_stripe_customer_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_9'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_8'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_7'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_6'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_5'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_4'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_3'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_20'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_2'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_19'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_18'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_17'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_16'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_15'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_14'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_13'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_12'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_11'), 'users', ['email'], unique=True)
    op.create_index(op.f('email_10'), 'users', ['email'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Last login timestamp',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('users', 'subscription_end_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Subscription expiration date',
               existing_nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.Enum('active', 'canceled', 'past_due', 'trialing', name='subscriptionstatus', native_enum=False),
               type_=mysql.ENUM('active', 'canceled', 'past_due', 'trialing'),
               comment=None,
               existing_comment='Current subscription status',
               existing_nullable=True)
    op.alter_column('users', 'subscription_id',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Active subscription ID',
               existing_nullable=True)
    op.alter_column('users', 'stripe_customer_id',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Stripe customer ID (legacy)',
               existing_nullable=True)
    op.alter_column('users', 'conversions_limit',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Monthly conversion limit',
               existing_nullable=False,
               existing_server_default=sa.text("'3'"))
    op.alter_column('users', 'conversions_used',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Number of conversions used this month',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'plan',
               existing_type=sa.Enum('free', 'starter', 'pro', 'enterprise', name='userplan', native_enum=False),
               type_=mysql.ENUM('free', 'starter', 'pro', 'enterprise'),
               comment=None,
               existing_comment='Current subscription plan',
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="User's display name",
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt hashed password',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment="User's email address",
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36),
               comment=None,
               existing_comment='Unique user identifier (UUID)',
               existing_nullable=False)
    op.drop_constraint(None, 'conversion_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_conversion_jobs_user_id'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_status'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_expires_at'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_created_at'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_cloudconvert_job_id'), table_name='conversion_jobs')
    op.create_index(op.f('conversion_jobs_user_id'), 'conversion_jobs', ['user_id'], unique=False)
    op.alter_column('conversion_jobs', 'status',
               existing_type=sa.Enum('pending', 'queued', 'processing', 'completed', 'failed', name='jobstatus', native_enum=False),
               type_=mysql.ENUM('pending', 'queued', 'processing', 'completed', 'failed'),
               existing_comment='Current job status',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('conversion_jobs', 'type',
               existing_type=sa.Enum('pdf_to_pptx', 'pdf_to_docx', 'pdf_to_xlsx', 'pdf_to_images', 'pdf_merge', name='conversiontype', native_enum=False),
               type_=mysql.ENUM('pdf_to_pptx', 'pdf_to_docx', 'pdf_to_xlsx', 'pdf_to_images', 'pdf_merge'),
               existing_comment='Type of conversion',
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_logs_user_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_transaction_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_subscription_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_status'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_payfast_payment_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_created_at'), table_name='payment_logs')
    op.drop_table('payment_logs')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_payfast_token'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_billing_date'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
